default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: movie_reservation_system_development

test:
  <<: *default
  database: movie_reservation_system_test

production:
  <<: *default
  database: movie_reservation_system_production
  username: movie_reservation_system
  password: <%= ENV['MOVIE_RESERVATION_SYSTEM_DATABASE_PASSWORD'] %>
